---

- name: "03.1.1 - make sure website's directory exists and properly configured"
  file:
    path: "{{ __nginx_websites_root_dir }}"
    state: directory
    recurse: no
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_group }}"
    mode: "ug=rwX,o=rX"
  become: yes

- name: "03.1.2 - make sure required config directories exists and properly configured"
  file:
    dest: "{{ item }}"
    state: directory
    recurse: yes
    owner: 0
    group: 0
  become: yes
  loop:
    - "{{ __nginx_config_dir }}"
    - "{{ __nginx_conf_d_dir }}"
    - "{{ __nginx_ssl_dir }}"

- name: "03.2 - make sure Diffie-Hellman Parameters file is generated"
  openssl_dhparam:
    path: "{{ __nginx_ssl_dhparam_file }}"
    size: "{{ __nginx_ssl_dhparam_size }}"
  become: yes

- name: "03.3 - place additional certificate files into SSL sub-dir"
  copy:
    dest: "{{ __nginx_ssl_dir }}/{{ item.name }}"
    content: "{{ item.content }}"
  become: yes
  loop_control:
    label: "{{ __nginx_ssl_dir }}/{{ item.name }}"
  loop: "{{ nginx_certificates|flatten(1) }}"

- name: "03.4 - template nginx server config"
  template:
    src: nginx.conf.j2
    dest: "{{ __nginx_config_file }}"
    backup: yes
    mode: "ug=rwX,o-rwx"
  become: yes
  notify:
    - nginx-test-config
    - nginx-reload-service

- meta: flush_handlers