---

- name: "04.1 - make sure default vhost is removed"
  file:
    path: "{{ __nginx_conf_d_dir }}/default.conf"
    state: absent
  become: yes
  notify:
    - nginx-test-config
    - nginx-reload-service

- name: "04.2 - template vhosts config-files"
  template:
    src: nginx.vhost.j2
    dest: "{{ __nginx_conf_d_dir }}/{{ item.name }}.vhost.conf"
  become: yes
  notify:
    - nginx-test-config
    - nginx-reload-service
  loop_control:
    label: "{{ item.name }}.vhost.conf"
  loop: "{{ nginx_vhosts|flatten(1) }}"

- name: "04.3.1 - find exists vhosts config-files"
  find:
    paths:
      - "{{ __nginx_conf_d_dir }}"
    recurse: no
    hidden: yes
    patterns: "*.vhost.conf"
    use_regex: no
    file_type: file
  register: _vhost_config_files
  become: yes

- name: "04.3.2 - delete files which are not in the list of configured vhosts"
  file:
    path: "{{ item.path }}"
    state: absent
    force: yes
    recurse: yes
  notify:
    - nginx-test-config
    - nginx-reload-service
  when:
    - ((item.path|basename).split('.vhost.conf'))[0] not in nginx_vhosts|map(attribute='name')|list
  loop_control:
    label: "{{ item.path }}"
  loop: "{{ _vhost_config_files.files|flatten(1) }}"
  become: yes

- meta: flush_handlers
