---

- name: "04.1 - template vhosts configs"
  template:
    src: nginx.vhost.j2
    dest: "{{ __nginx_vhosts_conf_dir }}/{{ item.name }}"
  become: yes
  notify:
    - nginx-test-config
    - nginx-reload-service
  loop: "{{ nginx_vhosts|flatten(1) }}"

- name: "04.2 - create symlink to enable vhosts"
  file:
    src: "{{ __nginx_vhosts_conf_dir }}/{{ item.name }}"
    dest: "{{ __nginx_vhosts_enabled_dir }}/{{ item.name }}"
    state: link
    force: yes
  become: yes
  notify:
    - nginx-test-config
    - nginx-reload-service
  loop: "{{ nginx_vhosts|flatten(1) }}"
  when:
    - __nginx_vhosts_enabled_dir != __nginx_conf_d_dir

- name: "04.3.1 - find all files in the vhosts dir"
  find:
    paths:
      - "{{ __nginx_vhosts_enabled_dir }}"
    recurse: no
    hidden: yes
    patterns: "*"
    use_regex: no
    file_type: any
  register: _vhost_config_files
  become: yes

- name: "04.3.2 - delete files which are not in the list of enabled"
  file:
    path: "{{ item.path }}"
    state: absent
    force: yes
    recurse: yes
  notify:
    - nginx-test-config
    - nginx-reload-service
  when:
    - item.path|basename not in nginx_vhosts|map(attribute='name')|list
  loop: "{{ _vhost_config_files.files }}"
  become: yes

- meta: flush_handlers
