---

- include_tasks: 01-prepare-env.yml

- include_tasks: 02-setup-packages.yml

- include_tasks: 03-configure-server.yml

- include_tasks: 04-configure-vhosts.yml

- name: "0.5 - make sure nginx is enabled and started"
  service:
    name: "{{ __nginx_service_name }}"
    state: started
    enabled: yes
  become: yes
