---

- include_tasks: 01-prepare-env.yml

- include_tasks: 02-setup-packages.yml

- include_tasks: 03-configure-server.yml

- include_tasks: 04-configure-vhosts.yml

- name: "0.5.(service) - manage state of nginx service"
  service:
    name: "{{ nginx_service_name }}"
    state: "{{ 'stopped' if nginx_package_state|string|lower == 'absent' else 'started' }}"
    enabled: "{{ False if nginx_package_state|string|lower == 'absent' else True }}"
  become: True
  ignore_errors: "{{ True if nginx_package_state|string|lower == 'absent' else False }}"
