---

- include_tasks: 01-prepare-env.yaml

- include_tasks: 02-setup-packages.yaml

- include_tasks: 03-configure-server.yaml

- include_tasks: 04-configure-vhosts.yaml

- name: "0.5 - make sure nginx is enabled and started"
  service:
    name: "{{ __nginx_service_name }}"
    state: started
    enabled: yes
  become: yes
