---
# file: handlers/main.yml

# Note: set cache_valid_time=0 to ensure that an apt-get update after the added repo-key else you often get
# 'WARNING: The following packages cannot be authenticated!
# See also: http://askubuntu.com/questions/75565/why-am-i-getting-authentication-errors-for-packages-from-an-ubuntu-repository
- name: "nginx-update-apt-cache"
  apt:
    update_cache: yes
    cache_valid_time: 0
  become: yes
  ignore_errors: yes

- name: "nginx-test-config"
  shell:
    "nginx -t -c {{ nginx_config_file }}"
  become: yes

- name: "nginx-reload-service"
  service:
    name: "{{ nginx_service_name }}"
    state: reloaded
  become: yes

- name: "nginx-restart-service"
  service:
    name: "{{ nginx_service_name }}"
    state: restarted
  become: yes
